version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: